# Generated by Django 3.0.14 on 2022-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='default', max_length=200)),
                ('laname', models.CharField(default='default', max_length=200)),
                ('email', models.CharField(default='default', max_length=200)),
                ('address', models.CharField(default='default', max_length=200)),
                ('phone', models.CharField(default='default', max_length=10)),
                ('username', models.CharField(default='default', max_length=100)),
                ('password', models.CharField(default='default', max_length=30)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
