# Generated by Django 3.0.14 on 2022-01-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
