# Generated by Django 3.0.14 on 2022-01-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20220130_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderproduct',
            table='orderproduct',
        ),
    ]
