# Generated by Django 3.0.14 on 2022-01-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_order_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_completed',
            new_name='order_placed',
        ),
    ]
