# Generated by Django 3.0.14 on 2022-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20220131_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Pending', max_length=200, null=True),
        ),
    ]
