# Generated by Django 3.0.14 on 2022-02-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20220201_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Order'),
        ),
    ]
