# Generated by Django 3.0.14 on 2022-01-29 09:12

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Childrens', 'Childrens'), ('New Arrival', 'New Arrival'), ('Self Help', 'Self Help'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Health and Fitness', 'Health and Fitness'), ('Politics', 'Politics'), ('Popular right now', 'Popular right now')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=django.forms.fields.ImageField),
        ),
    ]
