# Generated by Django 3.0.14 on 2022-02-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220131_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='iimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Childrens', 'Childrens'), ('New Arrival', 'New Arrival'), ('Self Help', 'Self Help'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Health and Fitness', 'Health and Fitness'), ('History', 'History'), ('Popular right now', 'Popular right now')], max_length=200, null=True),
        ),
    ]
