# Generated by Django 3.0.14 on 2022-02-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220210_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='iimage',
            new_name='image',
        ),
    ]
